version: "3.8"
services:
    marketplace:
        build:
            context: .
            dockerfile: marketplace/Dockerfile
        environment:
            RECOMMENDATIONS_HOST: recommendations
        image: marketplace
        networks:
            - microservices
        ports:
            - 5001:5000
        volumes:
            - ./marketplace:/service/marketplace

    recommendations:
        build:
            context: .
            dockerfile: recommendations/Dockerfile
        image: recommendations
        networks:
            - microservices
        volumes:
            - ./recommendations:/service/recommendations

networks:
    microservices:
