[tool.poetry]
name = "recommendations"
version = "0.1.0"
description = ""
authors = ["ThangTD"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
grpcio-tools = "^1.56.0"
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
